language: c
compiler:
  - clang
  - gcc
install: 
  - sudo apt-get install -qq libzookeeper-mt-dev libzookeeper-mt2
script: 
  - ./configure
  - make
notifications:
  email:
    - jinoos@gmail.com
    - jinoos@11st.co.kr
